const fields = {
  email: 'email',
  password: 'password',
  firstName: 'firstName',
  lastName: 'lastName',
  birthday: 'birthdate',
  courseTitle: 'courseTitle',
  courseDescription: 'courseDescription',
  courseDateRestriction: 'courseDateRestriction',
  courseIsprivate: 'courseIsprivate',
  sectionTitle: 'sectionTitle',
  sectionDescription: 'sectionDescription',
  sectionDateRestriction: 'sectionDateRestriction',
  sectionIsprivate: 'sectionIsprivate',
  announcementTitle: 'announcementTitle',
  announcementContent: 'announcementContent',
  lessonTitle: 'lessonTitle',
  lessonDescription: 'lessonDescription',
  lessonDate: 'lessonDate',
  lessonOrder: 'lessonOrder',
  lessonBody: 'lessonBody',
  lessonIframes: 'lessonIframes',
  lessonIframesTitle: 'lessonIframesTitle',
};

export default fields;
